import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { translate as __ } from 'foremanReact/common/I18n';
import {
  Card,
  CardBody,
  CardHeader,
  CardTitle,
  CodeBlock,
  CodeBlockCode,
  EmptyState,
  EmptyStateVariant,
  EmptyStateIcon,
  EmptyStateHeader,
  EmptyStateBody,
  Button,
  Tabs,
  Tab,
  TabTitleText,
  TabTitleIcon,
  Alert
} from '@patternfly/react-core';
import { 
  ExclamationCircleIcon, 
  CodeIcon, 
  FileAltIcon,
  CopyIcon 
} from '@patternfly/react-icons';

const CopyButton = ({ getText }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(getText()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <Button variant="control" aria-label="Copy" onClick={handleCopy} icon={<CopyIcon />}>
      {copied ? __('Copied!') : __('Copy')}
    </Button>
  );
};

const ResultDisplay = ({ jobResult, jobLog }) => {
  const [activeTabKey, setActiveTabKey] = useState(0);

  const formatResult = (result) => {
    if (!result) return '';
    try {
      return JSON.stringify(result, null, 2);
    } catch (error) {
      console.error('Error formatting result JSON:', error);
      return String(result);
    }
  };

  const resultJson = formatResult(jobResult);
  const hasResult = jobResult && Object.keys(jobResult).length > 0;
  const hasLog = jobLog?.trim?.().length > 0;

  const EmptyTab = ({ message }) => (
    <div className="pf-v5-u-mt-md">
      <EmptyState variant={EmptyStateVariant.sm}>
        <EmptyStateHeader 
          titleText={__('No data available')}
          icon={<EmptyStateIcon icon={ExclamationCircleIcon} />}
          headingLevel="h5"
        />
        <EmptyStateBody>{message}</EmptyStateBody>
      </EmptyState>
    </div>
  );

  const DataTab = ({ content }) => (
    <div className="pf-v5-u-mt-md">
      <div className="pf-v5-u-display-flex pf-v5-u-justify-content-flex-start pf-v5-u-mb-sm">
        <CopyButton getText={() => content} />
      </div>
      <CodeBlock>
        <CodeBlockCode>{content}</CodeBlockCode>
      </CodeBlock>
    </div>
  );

  return (
    <Card className="pf-v5-u-mb-md">
      <CardHeader>
        <CardTitle>{__('Task Output')}</CardTitle>
      </CardHeader>
      <CardBody>
        <Tabs
          activeKey={activeTabKey}
          onSelect={(_event, tabIndex) => setActiveTabKey(tabIndex)}
        >
          <Tab
            eventKey={0}
            title={<><TabTitleIcon><CodeIcon /></TabTitleIcon><TabTitleText>{__('Result')}</TabTitleText></>}
          >
            {hasResult ? (
              <DataTab content={resultJson} />
            ) : (
              <EmptyTab message={__('No result data returned from the task.')} />
            )}
          </Tab>
          
          <Tab
            eventKey={1}
            title={<><TabTitleIcon><FileAltIcon /></TabTitleIcon><TabTitleText>{__('Log Output')}</TabTitleText></>}
          >
            {hasLog ? (
              <DataTab content={jobLog} />
            ) : (
              <EmptyTab message={__('No log output generated by the task.')} />
            )}
          </Tab>
        </Tabs>
      </CardBody>
    </Card>
  );
};

ResultDisplay.propTypes = {
  jobResult: PropTypes.object,
  jobLog: PropTypes.string
};

export default ResultDisplay;
