inherit_gem:
  theforeman-rubocop:
    - default.yml
    - rules/style_lenient.yml

#cleanup once those are merged:
# * https://github.com/theforeman/theforeman-rubocop/pull/54
# * https://github.com/theforeman/theforeman-rubocop/pull/16
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - '**/*.spec'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.vendor/**/*'

Rails/RakeEnvironment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Max: 160
