#! /bin/bash

rm -rf ~/rpmbuild
rpmdev-setuptree
gem build foreman_openbolt.gemspec
cp foreman_openbolt-0.0.1.gem ~/rpmbuild/SOURCES/
gem2rpm -t foreman_openbolt.spec.erb ~/rpmbuild/SOURCES/foreman_openbolt-0.0.1.gem > ~/rpmbuild/SPECS/rubygem-foreman_openbolt.spec
rpmbuild -ba ~/rpmbuild/SPECS/rubygem-foreman_openbolt.spec
cp ~/rpmbuild/RPMS/noarch/rubygem-foreman_openbolt-0.0.1-1.el9.noarch.rpm .
