#! /bin/bash

rm -rf ~/rpmbuild
rpmdev-setuptree
gem build foreman_bolt.gemspec
cp foreman_bolt-0.0.1.gem ~/rpmbuild/SOURCES/
pushd /opt/foreman-packaging
gem2rpm -t gem2rpm/foreman_plugin.spec.erb ~/rpmbuild/SOURCES/foreman_bolt-0.0.1.gem > ~/rpmbuild/SPECS/rubygem-foreman_bolt.spec
popd

rpmbuild -ba ~/rpmbuild/SPECS/rubygem-foreman_bolt.spec
cp ~/rpmbuild/RPMS/noarch/rubygem-foreman_bolt-0.0.1-1.el9.noarch.rpm .
