import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { translate as __ } from 'foremanReact/common/I18n';
import {
  Button,
  Card,
  CardBody,
  CodeBlock,
  CodeBlockCode,
  EmptyState,
  EmptyStateVariant,
  EmptyStateIcon,
  EmptyStateHeader,
  EmptyStateBody,
  Tabs,
  Tab,
  TabTitleText,
  TabTitleIcon,
} from '@patternfly/react-core';
import {
  ClipboardCheckIcon,
  CopyIcon,
  ExclamationCircleIcon,
  FileAltIcon,
} from '@patternfly/react-icons';

const CopyButton = ({ getText }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    /* eslint-disable promise/prefer-await-to-then */
    navigator.clipboard.writeText(getText()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <Button
      variant="control"
      aria-label="Copy"
      onClick={handleCopy}
      icon={<CopyIcon />}
    >
      {copied ? __('Copied!') : __('Copy')}
    </Button>
  );
};

CopyButton.propTypes = {
  getText: PropTypes.func.isRequired,
};

const EmptyTab = ({ message }) => (
  <div className="pf-v5-u-mt-md">
    <EmptyState variant={EmptyStateVariant.sm}>
      <EmptyStateHeader
        titleText={__('No data available')}
        icon={<EmptyStateIcon icon={ExclamationCircleIcon} />}
        headingLevel="h5"
      />
      <EmptyStateBody>{message}</EmptyStateBody>
    </EmptyState>
  </div>
);

EmptyTab.propTypes = {
  message: PropTypes.string.isRequired,
};

const DataTab = ({ content }) => (
  <div className="pf-v5-u-mt-md">
    <CodeBlock>
      <CodeBlockCode>{content}</CodeBlockCode>
    </CodeBlock>
  </div>
);

DataTab.propTypes = {
  content: PropTypes.string.isRequired,
};

const ResultDisplay = ({ jobResult, jobLog }) => {
  const [activeTabKey, setActiveTabKey] = useState(0);

  const formatResult = result => {
    if (!result) return '';
    try {
      return JSON.stringify(result, null, 2);
    } catch (error) {
      return String(result);
    }
  };

  const resultJson = formatResult(jobResult);
  const hasResult = jobResult && Object.keys(jobResult).length > 0;
  const hasLog = jobLog?.trim?.().length > 0;

  const getActiveContent = () => (activeTabKey === 0 ? resultJson : jobLog);

  // A bit of a messy solution for the copy button but good enough for now
  return (
    <Card>
      <CardBody>
        <div style={{ position: 'relative' }}>
          <div
            style={{
              position: 'absolute',
              right: 0,
              zIndex: 1,
            }}
          >
            {((activeTabKey === 0 && hasResult) ||
              (activeTabKey === 1 && hasLog)) && (
              <CopyButton getText={getActiveContent} />
            )}
          </div>
          <Tabs
            activeKey={activeTabKey}
            onSelect={(_event, tabIndex) => setActiveTabKey(tabIndex)}
            actions={<CopyButton getText={getActiveContent} />}
          >
            <Tab
              eventKey={0}
              title={
                <>
                  <TabTitleIcon>
                    <ClipboardCheckIcon />
                  </TabTitleIcon>
                  <TabTitleText>{__('Result')}</TabTitleText>
                </>
              }
            >
              {hasResult ? (
                <DataTab content={resultJson} />
              ) : (
                <EmptyTab
                  message={__('No result data returned from the task.')}
                />
              )}
            </Tab>

            <Tab
              eventKey={1}
              title={
                <>
                  <TabTitleIcon>
                    <FileAltIcon />
                  </TabTitleIcon>
                  <TabTitleText>{__('Log Output')}</TabTitleText>
                </>
              }
            >
              {hasLog ? (
                <DataTab content={jobLog} />
              ) : (
                <EmptyTab
                  message={__('No log output generated by the task.')}
                />
              )}
            </Tab>
          </Tabs>
        </div>
      </CardBody>
    </Card>
  );
};

ResultDisplay.propTypes = {
  jobResult: PropTypes.object.isRequired,
  jobLog: PropTypes.string.isRequired,
};

export default ResultDisplay;
