---
name: CI

on:
  pull_request: {}

env:
  BUNDLE_WITHOUT: release

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run linters
        run: bundle exec rake lint:all LOCAL=true
      - name: Verify gem builds
        run: gem build --strict --verbose *.gemspec
